### ISSUE TITLE
/json/pkgsbreakingmostothers/N sometimes returns null

### ISSUE THREAD

**Issue by riastradh** [bsiegert/BulkTracker#67] opened 2024-06-22 13:27 UTC
```
$ curl -D - https://releng.netbsd.org/bulktracker/json/pkgsbreakingmostothers/901          
HTTP/1.1 200 OK
Date: Sat, 22 Jun 2024 13:25:42 GMT
Server: Apache/2.4.59 (Unix)
Content-Type: application/json
Content-Length: 5

null
```

Expected output: a (non-null) json object with a sorted array of package breakage relations.

Works for 900 and 902, but not 901.

**Comment by bsiegert** [comment] 2024-06-22 14:17
This happens when there is a problem reading the full report at the URL indicated. It is theoretically possible to trigger a refresh but the code path is actually commented out at the moment.

**Comment by riastradh** [comment] 2024-06-22 14:18
I see:

```
sqlite> select count(*) from results r where r.build_id = 901;
0
```

**Comment by bsiegert** [comment] 2024-06-22 14:20
I am going to close this as a duplicate of #5, since it is about the same thing.

**Comment by bsiegert** [comment] 2024-06-22 14:21
Duplicate of #5

**Closed as completed by bsiegert** 2024-06-22 14:21 UTC
